/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesWellnessRouteImport } from './routes/services.wellness'
import { Route as ServicesStylingRouteImport } from './routes/services.styling'
import { Route as ServicesHeritageRouteImport } from './routes/services.heritage'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as ApiPublicConfigRouteImport } from './routes/api/public/config'
import { Route as ApiPublicBookingEmailRouteImport } from './routes/api/public/booking-email'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWellnessRoute = ServicesWellnessRouteImport.update({
  id: '/services/wellness',
  path: '/services/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStylingRoute = ServicesStylingRouteImport.update({
  id: '/services/styling',
  path: '/services/styling',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHeritageRoute = ServicesHeritageRouteImport.update({
  id: '/services/heritage',
  path: '/services/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public/config',
  path: '/api/public/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingEmailRoute = ApiPublicBookingEmailRouteImport.update({
  id: '/api/public/booking-email',
  path: '/api/public/booking-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/services/heritage': typeof ServicesHeritageRoute
  '/services/styling': typeof ServicesStylingRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/booking-email': typeof ApiPublicBookingEmailRoute
  '/api/public/config': typeof ApiPublicConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/services/heritage': typeof ServicesHeritageRoute
  '/services/styling': typeof ServicesStylingRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/booking-email': typeof ApiPublicBookingEmailRoute
  '/api/public/config': typeof ApiPublicConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/services/heritage': typeof ServicesHeritageRoute
  '/services/styling': typeof ServicesStylingRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/booking-email': typeof ApiPublicBookingEmailRoute
  '/api/public/config': typeof ApiPublicConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/portfolio'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/reset-password'
    | '/services/heritage'
    | '/services/styling'
    | '/services/wellness'
    | '/admin/'
    | '/api/public/booking-email'
    | '/api/public/config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/portfolio'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/reset-password'
    | '/services/heritage'
    | '/services/styling'
    | '/services/wellness'
    | '/admin'
    | '/api/public/booking-email'
    | '/api/public/config'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/portfolio'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/login'
    | '/admin/reset-password'
    | '/services/heritage'
    | '/services/styling'
    | '/services/wellness'
    | '/admin/'
    | '/api/public/booking-email'
    | '/api/public/config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  ServicesHeritageRoute: typeof ServicesHeritageRoute
  ServicesStylingRoute: typeof ServicesStylingRoute
  ServicesWellnessRoute: typeof ServicesWellnessRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicBookingEmailRoute: typeof ApiPublicBookingEmailRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/wellness': {
      id: '/services/wellness'
      path: '/services/wellness'
      fullPath: '/services/wellness'
      preLoaderRoute: typeof ServicesWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/styling': {
      id: '/services/styling'
      path: '/services/styling'
      fullPath: '/services/styling'
      preLoaderRoute: typeof ServicesStylingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/heritage': {
      id: '/services/heritage'
      path: '/services/heritage'
      fullPath: '/services/heritage'
      preLoaderRoute: typeof ServicesHeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/config': {
      id: '/api/public/config'
      path: '/api/public/config'
      fullPath: '/api/public/config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-email': {
      id: '/api/public/booking-email'
      path: '/api/public/booking-email'
      fullPath: '/api/public/booking-email'
      preLoaderRoute: typeof ApiPublicBookingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  ServicesHeritageRoute: ServicesHeritageRoute,
  ServicesStylingRoute: ServicesStylingRoute,
  ServicesWellnessRoute: ServicesWellnessRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicBookingEmailRoute: ApiPublicBookingEmailRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
